"""add date,modulName to Point

Revision ID: 043f2a58dccf
Revises: ab388cb38069
Create Date: 2019-12-23 19:27:42.061115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043f2a58dccf'
down_revision = 'ab388cb38069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('date', sa.String(length=256), nullable=True))
    op.add_column('point', sa.Column('modulName', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'modulName')
    op.drop_column('point', 'date')
    # ### end Alembic commands ###
