"""add column for digitalIn(A,B,C,D)

Revision ID: 28d91d087939
Revises: 83946c17087a
Create Date: 2019-12-16 10:47:07.269805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d91d087939'
down_revision = '83946c17087a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('digInA', sa.String(length=64), nullable=True))
    op.add_column('point', sa.Column('digInB', sa.String(length=64), nullable=True))
    op.add_column('point', sa.Column('digInC', sa.String(length=64), nullable=True))
    op.add_column('point', sa.Column('digInD', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'digInD')
    op.drop_column('point', 'digInC')
    op.drop_column('point', 'digInB')
    op.drop_column('point', 'digInA')
    # ### end Alembic commands ###
