"""first commit

Revision ID: 83946c17087a
Revises: 
Create Date: 2019-12-15 19:02:54.767985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83946c17087a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pointname', sa.String(length=64), nullable=True),
    sa.Column('volt1', sa.String(length=64), nullable=True),
    sa.Column('volt2', sa.String(length=64), nullable=True),
    sa.Column('temp', sa.String(length=64), nullable=True),
    sa.Column('load1', sa.String(length=64), nullable=True),
    sa.Column('load2', sa.String(length=64), nullable=True),
    sa.Column('load3', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_pointname'), 'point', ['pointname'], unique=True)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.String(length=140), nullable=True),
    sa.Column('temperature', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_timestamp'), 'data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_timestamp'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_point_pointname'), table_name='point')
    op.drop_table('point')
    # ### end Alembic commands ###
